extends: site.yaml
mode: production
publisher:
    zip:
        type: hyde.ext.publishers.pyfs.PyFS
        url: zip://~/www_publish.zip
    sftp:
        type: hyde.ext.publishers.pyfs.PyFS
        url: sftp://kellerbw@physwww.mcmaster.ca
